version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}
services:
#PHP
    php-fpm:
        build:
          context: ./php-fpm
        volumes:
          - ../src:/var/www

#NGINX
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
          - ../src:/var/www
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/sites/:/etc/nginx/sites-available
          - ./nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
          - php-fpm
        ports:
          - 7070:443
          - 8080:80
        
#MYSQL
    database:
        restart: always
        image: mariadb:latest
        ports:
         - 3306:3306
        environment:
          - MYSQL_DATABASE=my_db
          - MYSQL_USER=my_user
          - MYSQL_PASSWORD=my_password
          - MYSQL_ROOT_PASSWORD=rootpass
        volumes:
          - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
          - /var/run/docker.sock:/var/run/docker.sock
      
#GRAFANA      
    grafana:
        restart: always
        image: grafana/grafana
        depends_on:
          - prometheus
        ports:
          - 3000:3000
        volumes:
          - grafana_data:/var/lib/grafana
          - ./grafana/grafana.ini:/etc/grafana/grafana.ini
          - ./grafana/provisioning/:/etc/grafana/provisioning/

#PROMETHEUS
    prometheus:
        image: prom/prometheus
        ports:
          - 9090:9090
        volumes:
          - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
          - prometheus_data:/prometheus
        depends_on:
          - nginx
#EXPORTER
    nginx-exporter:
        restart: always
        image: nginx/nginx-prometheus-exporter:0.2.0
        depends_on:
          - nginx
        command:
          -nginx.scrape-uri=http://nginx:80/nginx_stats
          -web.telemetry-path=/metrics
        ports:
            - 9113:9113
            
networks:
  default:
    name: "project_net"